version: '2'
services:
  mariadb-dev:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
    volumes:
    - mariadb_data:/var/lib/mysql
  wordpress:
    image: wordpress:php7.3-fpm-alpine
    environment:
      WORDPRESS_DB_HOST: ${wordpress_db_host}
      WORDPRESS_DB_NAME: ${wordpress_db_name}
      WORDPRESS_DB_PASSWORD: ${wordpress_db_password}
    stdin_open: true
    tty: true
    volumes:
    - wordpress_data:/var/www/html
    depends_on:
    - mariadb-dev
    links:
    - mariadb-dev:wordpress_db
    labels:
      io.rancher.container.pull_image: always
  nginx:
    image: nginx:1.16.1-alpine
    links:
    - wordpress
    volumes:
    - wordpress_data:/var/www/html
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local