version: '2'
services:
  static-website:
    image: httpd:latest
    restart: always
    
    environment:
      RANCHER_URL: ${RANCHER_URL}
      RANCHER_ACCESS_KEY: ${RANCHER_ACCESS_KEY}
      RANCHER_SECRET_KEY: ${RANCHER_SECRET_KEY}
      RANCHER_ENVIRONMENT: ${RANCHER_ENVIRONMENT}
    stdin_open: true
    labels:
      io.rancher.container.pull_image: always

