version: '2'
services:
  redis:
    image: redis
    volumes:
    - redis_data:/data
  wordpress:
    image: dbrosy/wordpress:apache-cli
    environment:
      WORDPRESS_DB_HOST: ${wordpress_db_host}
      WORDPRESS_DB_NAME: ${wordpress_db_name}
      WORDPRESS_DB_PASSWORD: ${wordpress_db_password}
    stdin_open: true
    volumes:
    - wordpress_data:/var/www/html
    tty: true
    links:
    - wp-shared/mariadb:wordpress_db
    labels:
      io.rancher.container.pull_image: always
volumes:
  redis_data:
    driver: local
  wordpress_data:
    driver: local
