version: '2'
catalog:
  name: "wp"
  version: "0.0.1-php72-wordpress-shared-stack-1"
  description: "Wordpress using a shared database"
  uuid: Wordpress-shared-1
  minimum_rancher_version: v1.1.0
  questions:
    - variable: wordpress_db_host
      description: "wordpress database host, set on first run"
      label: "Wordpress Database Host"
      required: true
      default: "mariadb"
      type: "string"
    - variable: wordpress_db_name
      description: "Wordpress database name, created on first run"
      label: "Wordpress Database Name"
      required: true
      default: "wp_"
      type: "string"
    - variable: wordpress_db_password
      description: "Wordpress database password, set on first run"
      label: "Wordpress Database Password"
      required: true
      default: ""
      type: "string"       
services:
  mariadb:
    hostname: mariadb.wp-shared.rancher.internal
    start_on_create: true
  wordpress:
    scale: 1
    start_on_create: true
  redis:
    scale: 1
    start_on_create: true
