version: '2'
volumes:
  mariadb_data:
    driver: local
services:
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
    volumes:
    - mariadb_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - mariadb:db
