version: '2'
catalog:
  name: "Wordpress mariadb"
  version: "v 0.1 dbrosy"
  description: "Testing"
  uuid: Wordpress-1
  minimum_rancher_version: v1.1.0
  questions:    
    - variable: mysql_root_password
      description: "MariaDB root password, set on first run"
      label: "MariaDB Root Password"
      required: true
      default: "Pa55w0rd"
      type: "string"
services:
  mariadb:
    scale: 1
    start_on_create: true
  wordpress:
    scale: 1
    start_on_create: true
  wordpress-lb:
    scale: 1
    start_on_create: false
    lb_config:
      certs: []
      default_cert: b.brosy.com
      port_rules:
      - hostname: b.brosy.com
        path: /.well-known/acme-challenge
        priority: 1
        protocol: http
        service: Certificates/letsencrypt
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      strategy: recreate
