name: Wordpress # Name of the Catalog Entry
description: |
  Wordpress stack for rancher. # Description of the Catalog Entry
version: 0.0.1 # Version of the Catalog to be used
category: Web # Category to be used for searching catalog entries
maintainer: Damian Brosnahan # The maintainer of the catalog entry
license: # The license
projectURL: https://github.com/dbrosy/rancher-catalog # A URL related to the catalog entry

