version: '2'
catalog:
  name: "wp"
  version: "0.0.2-php71-wordpress-shared-stack-1"
  description: "Wordpress using a shared database"
  uuid: Wordpress-shared-1
  minimum_rancher_version: v1.1.0
  questions:
    - variable: WORDPRESS_DB_HOST
      description: "wordpress database host, set on first run"
      label: "Wordpress Database Host"
      required: true
      default: "mariadb"
      type: "string"
    - variable: WORDPRESS_DB_NAME
      description: "Wordpress database name, created on first run"
      label: "Wordpress Database Name"
      required: true
      default: "wp_"
      type: "string"
    - variable: WORDPRESS_DB_PASSWORD
      description: "Wordpress database password, set on first run"
      label: "Wordpress Database Password"
      required: true
      default: ""
      type: "string"
    - variable: DOMAIN_NAME_1
      description: "Wordpress Domain Name, eg. example.com"
      label: "Domain Name 1"
      required: true
      default: ""
      type: "string"
    - variable: DOMAIN_NAME_2
      description: "Wordpress Domain Name, eg. www.example.com"
      label: "Domain Name 2"
      required: false
      default: ""
      type: "string"                  
services:
  mariadb:
    hostname: mariadb.wp-shared.rancher.internal
    start_on_create: true
  wordpress:
    scale: 1
    start_on_create: true
  redis:
    scale: 1
    start_on_create: true
  lb-https:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ${DOMAIN_NAME_1}
        priority: 1
        protocol: http
        service: wordpress
        source_port: 80
        target_port: 80
      - hostname: ${DOMAIN_NAME_2}
        priority: 1
        protocol: http
        service: wordpress
        source_port: 80
        target_port: 80        
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000