version: '2'
volumes:
  redis_data:
    driver: local
  wordpress_data:
    driver: local
services:
  mariadb:
    image: rancher/external-service
  redis:
    image: redis
    volumes:
    - redis_data:/data
  wordpress:
    image: dbrosy/wordpress:php5.6-apache-cli
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    stdin_open: true
    volumes:
    - wordpress_data:/var/www/html
    tty: true
    links:
    - mariadb:wordpress_db
    labels:
      io.rancher.container.pull_image: always
  lb-https:
    image: rancher/lb-service-haproxy:v0.7.15
    expose:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      web.https: 'true'